### ISSUE TITLE
Investigate improvements for small-screen users

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#75]
get more info on device, browser, screen size, resolution for users having issues.
Consider possibilities to improve layout 
Discuss potential options to improve

**Comment by kschelonka** [comment]
I've investigated the issue, and I think we should take the following steps:

1. Improve our reactive layout with Bootstrap flex grid
2. Use the reactive features in Highcharts for the trace chart
3. Stack the image panes in reverse order on small screens so that the video stays on the bottom (closest to the trace)
4. Make the brightness and contrast sliders in a single row rather than two to reduce vertical space
5. Add instructions for the user to zoom out if their browser zoom level is greater than 100% and they are having trouble seeing the

**Comment by kschelonka** [comment]
@wbwakeman I think all these tasks together are probably a 5 point story. Since a few users have brought up the issues already I think these changes should take high priority with respect to the segmentation labeling app work. Would it be ok if I added these to the current sprint backlog?

**Comment by wbwakeman** [comment]
@kschelonka sounds good to me.
